import Head from "next/head";
import Image from "next/image";
import FlightSearch from "../components/flight-search";
import styles from "../styles/Home.module.css";

//========================================================
export default function Home() {
  return (
    <>
      <Head>
        <title>Test Flight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image
          style={{ width: "100%" }}
          width={500}
          height={200}
          src="/banner-for-travel-agency.jpg"
          alt="failed..."
        />

        <FlightSearch />
      </main>
    </>
  );
}
//========================================================
